#include "RandGen.h"
#include "cli_args.h"

using namespace xvmt;

#include <array>
#include <memory>
#include <iostream>
#include <fstream>
#include <iomanip>

// This is the initialization seed. Refer to the original MT19937 documentation.
const uint32_t seedlength = 4;
const uint32_t seedinit[seedlength] = { 0x123, 0x234, 0x345, 0x456 };

// show how to construct and use a geneartor with VecLen=128 and GenMode=QM_Block16
void demo128()
{
    std::cout << "example of how to use the generator with M=4 and SSE2 instructions\n";

    /*
        We use a jump ahead polynomial mask of 2^1993X values, where X=log2(M)
        Use the following masks, depending on the chosen number of bits :
            32 = > nullptr
            128 = > ./dat/mt32/J19935.mt32.bits
            256 = > ./dat/mt32/J19934.mt32.bits
            512 = > ./dat/mt32/J19933.mt32.bits

        With VecLen=128 bits we have M=128/32=4 state vectors.
        With M=4 we have X=5, i.e. we use the mask for jump ahead of 2^19935 values
    */
    typedef VMT19937<128, true>::poly_t poly_t;
    poly_t jumpPoly;
    std::ifstream is("./dat/mt32/J19935.mt32.bits", std::ios::binary);
    if (is) jumpPoly.fromBin(is);

    /*
        Create the generator
    */
    VMT19937<128, true> mt(seedinit, seedlength, (const poly_t*)nullptr, &jumpPoly);

    // Create storage vector aligned with cache lines, where we will store results
    AlignedVector<uint32_t, 64> buffer(16);

    // Query 10 times the generator in blocks of 16 numbers
    for (size_t i = 0; i < 10; ++i) {
        mt.genrand_uint32_blk16(buffer.data());
        for (size_t j = 0; j < 16; ++j)
            std::cout << buffer[j] << ", ";
    }
    std::cout << "\n";
}

// show how to construct multiple independent generators
void demoParallel()
{
    std::cout << "example of how to use multiple independent generators\n";

    typedef VMT19937<128, true>::poly_t poly_t;

    // Get the relevant jump mask. With 128 bits registers we pick J19935.mt32.bits
    poly_t jumpPoly;
    std::ifstream is("./dat/mt32/J19935.mt32.bits", std::ios::binary);
    if (is) jumpPoly.fromBin(is);

    // Get the chosen common jump mask. The size of the jump determines the period
    // before the stream generated by multiple generators become overlapping.
    // In this example we use the J00100.mt32.bits mask.
    poly_t commonPoly;
    std::ifstream isC("./dat/mt32/J00100.mt32.bits", std::ios::binary);
    if (isC) commonPoly.fromBin(isC);

    // an array of parallel independent generators, which are guaranteed not to be overlapping
    // up to a period of 2^100
    std::array<std::unique_ptr<VMT19937<128, true>>, 10> parallelGenerators;

    // Create 10 multiple parallel generators with VecLen=128 and QueryMode=Block16
    for (size_t i = 0; i < 10; ++i) {
        // We use commonPoly as the sequential jump mask for the 10 streams
        parallelGenerators[i].reset(new VMT19937<128, true>(seedinit, seedlength, &commonPoly, &jumpPoly));
    }

    // Create storage vector aligned with cache lines, where we will store results
    AlignedVector<uint32_t, 64> buffer(16);

    // Query 10 times each of the generators in blocks of 16
    // We could also use mt.genrand_uint32(), which queries one number at a time, but it is slower.
    for (auto& g : parallelGenerators) {
        for (size_t i = 0; i < 10; ++i) {
            g->genrand_uint32_blk16(buffer.data());
            for (size_t j = 0; j < 16; ++j)
                std::cout << buffer[j] << ", ";
        }
        std::cout << "\n";
    }
}

// show how to use the multi-state 64-bit MT19937 generator (VMT19937_64)
void demoVMT64()
{
    std::cout << "example of how to use the multi-state 64-bit MT19937 generator (VMT19937_64)\n";

    /*
        VMT19937_64<128> uses a 128-bit virtual register with M=128/64=2 parallel 64-bit MT states.
        The sequential jump mask separates each state by 2^19936 values so they never overlap.

        Number of states by VecLen:
            128 => 2 states, use ./dat/mt64/J19936.mt64.bits
            256 => 4 states, use ./dat/mt64/J19935.mt64.bits
            512 => 8 states, use ./dat/mt64/J19934.mt64.bits
    */
    typedef VMT19937_64<128, true>::poly_t poly_t;
    poly_t jumpPoly;
    std::ifstream is("./dat/mt64/J19936.mt64.bits", std::ios::binary);
    if (is) jumpPoly.fromBin(is);

    // Create the generator with VecLen=128 and block-query mode
    VMT19937_64<128, true> gen(uint64_t(5489), (const poly_t*)nullptr, &jumpPoly);

    // Create aligned storage for one cache line of uint64_t values (8 x 8 bytes)
    AlignedVector<uint64_t, 64> buffer(8);

    // Query 5 times in blocks of 8 numbers
    for (size_t i = 0; i < 5; ++i) {
        gen.genrand_word_blk(buffer.data());
        for (size_t j = 0; j < 8; ++j)
            std::cout << buffer[j] << ", ";
        std::cout << "\n";
    }
}

// show how to use single-state 64-bit MT19937 generator with 128-bit SIMD registers
void demo128_64()
{
    std::cout << "example of how to use a single 64-bit MT generator with 128-bit registers\n";

    /*
        This generator uses SIMD registers but runs only ONE MT19937-64 state.
        This is useful for legacy code that expects a single stream but wants SIMD speed.
    */
    XMT19937_64<SIMD_ISA, true> gen;
    gen.reinit(uint64_t(5489), (const XMT19937_64<>::poly_t*)nullptr, nullptr);

    AlignedVector<uint64_t, 64> buffer(8);
    gen.genrand_word_blk(buffer.data());

    for (size_t j = 0; j < 8; ++j)
        std::cout << buffer[j] << ", ";
    std::cout << "\n";
}

int main(int argc, const char** argv)
{
    // show single-state 32-bit MT19937 generator
    demo128();
    std::cout << "\n\n\n";

    // show how to use multiple independent generators
    demoParallel();
    std::cout << "\n\n\n";

    // show multi-state 64-bit MT19937 generator
    demoVMT64();
    std::cout << "\n\n\n";

    // show single-state 64-bit MT19937 generator
    demo128_64();

    return 0;
}
